In [2]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
n_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
print(n_array.ndim)
print(n_array.shape)

2
(2, 5)


In [4]:
import torch
t_array = torch.FloatTensor(n_array)


In [5]:
t_array

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [6]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())

torch.Size([2, 5])
2
torch.Size([2, 5])


In [7]:
t_array[1:]

tensor([[5., 6., 7., 8., 9.]])

In [8]:
t_array[:2,:3]

tensor([[0., 1., 2.],
        [5., 6., 7.]])

In [9]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)

In [10]:
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)
print(f'Shape of t1: {t1.shape}')
print(f'Shape of t2: {t2.shape}')

Shape of t1: torch.Size([2, 5])
Shape of t2: torch.Size([5, 2])


In [11]:
print(t1.matmul(t2))

tensor([[ 60.,  70.],
        [160., 195.]])


In [12]:
print(t1)
print(t2)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])


In [13]:
n1.dot(n2)

array([[ 60,  70],
       [160, 195]])

In [14]:
n1 = np.arange(4).reshape(2,2)
n2 = np.arange(4).reshape(2,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 * t2

tensor([[0., 1.],
        [4., 9.]])

In [15]:
t1.mul(t2)

tensor([[0., 1.],
        [4., 9.]])

In [16]:
t1 * 5

tensor([[ 0.,  5.],
        [10., 15.]])

In [17]:
n1 = np.arange(10)
t1 = torch.FloatTensor(n1)
t1.mean()

tensor(4.5000)

In [18]:
n1 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t1.mean(dim=0)

tensor([4., 5.])

In [19]:
t1.mean(dim=1)

tensor([0.5000, 2.5000, 4.5000, 6.5000, 8.5000])

In [20]:
n1 = np.arange(10)
n1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
t1 = torch.FloatTensor(n1)
t1.view(-1,2)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [22]:
n1.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
t1.view(-1,10).shape

torch.Size([1, 10])

In [24]:
t1.view(-1,10).squeeze()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
import torch  ## tensor operation for ML/DL formula
import torch.nn.functional as F

In [26]:
tensor = torch.FloatTensor([0.5,0.7,0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [41]:
y = torch.randint(5,(10,5))
y_label = y.argmax(dim=1)

In [42]:
y_label

tensor([4, 2, 1, 1, 1, 3, 4, 1, 1, 1])

In [43]:
y

tensor([[1, 3, 1, 0, 4],
        [0, 1, 3, 3, 1],
        [0, 3, 2, 2, 1],
        [0, 2, 0, 2, 2],
        [2, 4, 0, 1, 2],
        [0, 3, 2, 4, 1],
        [3, 3, 2, 2, 4],
        [3, 4, 3, 0, 2],
        [1, 4, 1, 1, 0],
        [1, 2, 2, 1, 1]])

In [44]:
F.one_hot(y_label)

tensor([[0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0]])

In [46]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 2*y + 5

In [47]:
z.backward()

In [48]:
w.grad

tensor(8.)

In [50]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [51]:
Q = 3*a**3 - b**2

In [52]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [53]:
a.grad

tensor([36., 81.])

In [54]:
b.grad

tensor([-12.,  -8.])

In [55]:
import numpy as np
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1,1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1,1)

In [72]:
import torch
from torch.autograd import Variable
class LinearRegression(torch.nn.Module):
  def __init__(self, inputSize, outputSize):
    super(LinearRegression,self).__init__()
    self.linear = torch.nn.Linear(inputSize, outputSize)

  def forward(self,x):
    out = self.linear(x)
    return out

In [73]:
inputDim = 1 # takes variable 'x'
outputDim = 1 # takes variable 'y'
learningRate = 0.01
epochs = 100

model = LinearRegression(inputDim, outputDim)
#### For GPU ####
if torch.cuda.is_available():
  model.cuda()

In [74]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learningRate)

In [75]:
for epoch in range(epochs):
  # Coverting inputs and labels to Variable
  if torch.cuda.is_available():
    inputs = Variable(torch.from_numpy(x_train).cuda())
    labels = Variable(torch.from_numpy(y_train).cuda())
  else:
    inputs = Variable(torch.from_numpy(x_train))
    labels = Variable(torch.from_numpy(y_train))

  # Clear gradient buffers because we don't want any gradient from previous epoch to carry forward, dont want to cummulate graidents 
  optimizer.zero_grad()  #항상 해줘야함

  # get ouput from the model, given the inputs
  outputs= model(inputs)

  # get loss for the predicted output
  loss = criterion(outputs, labels)
  print(loss)
  # get gradients w.r.t to parameters
  loss.backward()

  # update parameters
  optimizer.step()

  print(f'epoch {epoch}, loss {loss.item()}')



tensor(49.6937, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 0, loss 49.69368362426758
tensor(4.2020, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 1, loss 4.201950550079346
tensor(0.4897, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 2, loss 0.4896758794784546
tensor(0.1852, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 3, loss 0.18523529171943665
tensor(0.1588, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 4, loss 0.15878066420555115
tensor(0.1550, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 5, loss 0.1550186723470688
tensor(0.1531, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 6, loss 0.15312522649765015
tensor(0.1514, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 7, loss 0.1514020711183548
tensor(0.1497, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 8, loss 0.14971037209033966
tensor(0.1480, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 9, loss 0.14803843200206757
tensor(0.1464, device='cuda:0', grad_fn=<MseLossBackward>)
epoch 10, loss 0.

In [76]:
with torch.no_grad(): # we don't need gradients in the testing phase
  if torch.cuda.is_available():
    predicted = model(Variable(torch.from_numpy(x_train).cuda())).cpu().data.numpy()
  else:
    predicted = model(Variable(torch.from_numpy(x_train))).data.numpy()
  print(predicted)

[[ 0.56819934]
 [ 2.6303825 ]
 [ 4.6925654 ]
 [ 6.754749  ]
 [ 8.816932  ]
 [10.879115  ]
 [12.9412985 ]
 [15.003481  ]
 [17.065664  ]
 [19.127848  ]
 [21.190031  ]]
